### PR TITLE
more stg functions, patch marks

### PR DESCRIPTION
**Pull request by jtatarik**
The rebase, as requested. It's quite difficult, as we were touching/implementing the same things.

### CODE REVIEW

**Comment by llvilanova** [comment]
I've added some improved support for patch marking, and ported `magit-stgit-delete` to it as an example. I might port the rest eventually, but feel free to work from that.

**Comment by llvilanova** [comment]
I've pushed some new changes supporting edition of existing patches (using "stg refresh", I've not added a command for "stg edit" since it seems unnecessary given "refresh").

**Comment by jtatarik** [comment]
If you refer to 'stg refresh -e' for editing the commit message, then that will not do. It modifes the message *and* refreshes at the same time...

**Comment by llvilanova** [comment]
That's true, silly me...

**Pull request closed without merging**
